// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJastQkFIyTYq5H1014K3H18ie6rblyI',
    appId: '1:35962434841:web:1f7dfdbcd3fc8a0e054188',
    messagingSenderId: '35962434841',
    projectId: 'fir-full-ea159',
    authDomain: 'fir-full-ea159.firebaseapp.com',
    storageBucket: 'fir-full-ea159.appspot.com',
    measurementId: 'G-5JKQVD3KR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFY1hZeXWfUbKDINz1TApIrIyGCLcUA2A',
    appId: '1:35962434841:android:0687b02b50efcd8f054188',
    messagingSenderId: '35962434841',
    projectId: 'fir-full-ea159',
    storageBucket: 'fir-full-ea159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7LpqZLerfnq3fNttzWaytMS5K1KVOiA',
    appId: '1:35962434841:ios:075db33331bd726f054188',
    messagingSenderId: '35962434841',
    projectId: 'fir-full-ea159',
    storageBucket: 'fir-full-ea159.appspot.com',
    iosBundleId: 'com.example.firebasefull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7LpqZLerfnq3fNttzWaytMS5K1KVOiA',
    appId: '1:35962434841:ios:418edc95e46bbc99054188',
    messagingSenderId: '35962434841',
    projectId: 'fir-full-ea159',
    storageBucket: 'fir-full-ea159.appspot.com',
    iosBundleId: 'com.example.firebasefull.RunnerTests',
  );
}
